/**
 * Production-Grade Next.js Configuration
 * SEO + Performance + Security optimizations + Sentry Error Tracking
 * Generated by 36 Agent Ecosystem
 */

const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

// Import Sentry webpack plugin for source maps upload
const { withSentryConfig } = require('@sentry/nextjs');

/** @type {import('next').NextConfig} */
const nextConfig = {
  // i18n configuration for Pages Router (required for getStaticPaths with locale)
  i18n: {
    locales: ['tr', 'en', 'de', 'ru', 'ar', 'fa', 'fr', 'el'],
    defaultLocale: 'tr',
    localeDetection: false,
  },

  // Fix workspace root detection issue
  outputFileTracingRoot: require('path').join(__dirname),

  // Strict mode for better SEO
  reactStrictMode: true,
  // swcMinify: true, // Removed - default in Next.js 15+

  // Experimental features for performance optimization
  experimental: {
    optimizePackageImports: [
      'lucide-react',
      'framer-motion',
      '@heroicons/react',
      'chart.js',
      'react-chartjs-2',
      'date-fns',
      'lodash',
    ],
    // Mobile performance optimizations
    optimizeCss: true,
    scrollRestoration: true,
  },

  // Compiler optimizations for better mobile performance
  compiler: {
    // Remove console logs in production
    removeConsole: process.env.NODE_ENV === 'production',
    // Minify emotion CSS
    emotion: true,
    // React compiler optimizations
    reactRemoveProperties: process.env.NODE_ENV === 'production',
  },

  // Externalize server-only packages for better performance (Next.js 15+)
  serverExternalPackages: [
    'winston',
    'puppeteer',
    'sharp',
    'prisma',
    '@prisma/client',
    'nodemailer',
    'cloudinary',
  ],

  // ESLint configuration
  eslint: {
    ignoreDuringBuilds: true,
    dirs: ['src'],
  },

  // TypeScript configuration
  typescript: {
    ignoreBuildErrors: true,
  },

  // Webpack configuration - Advanced optimization
  webpack: (config, { dev, isServer, webpack }) => {
    // ==================================================
    // CLIENT-SIDE: Node.js Polyfills & Optimizations
    // ==================================================
    if (!isServer) {
      // Strategy 1: Alias - Use polyfills for non-critical modules only
      config.resolve.alias = {
        ...config.resolve.alias,
        'path': require.resolve('./lib/polyfills/path-mock.js'),
        'os': require.resolve('./lib/os-mock.js'),
      };

      // Strategy 2: Fallback - Use npm packages for browser polyfills
      config.resolve.fallback = {
        ...config.resolve.fallback,
        // Core polyfills from npm packages
        buffer: require.resolve('buffer/'),
        process: require.resolve('process/browser.js'),
        stream: require.resolve('stream-browserify'),
        crypto: require.resolve('crypto-browserify'),
        util: require.resolve('util/'),
        // Use mock for fs instead of false to prevent runtime errors
        fs: require.resolve('./lib/polyfills/fs-mock.js'),
        // Disable other server-only modules
        net: false,
        tls: false,
        dns: false,
        http2: false,
        https: false,
        child_process: false,
        zlib: false,
      };

      // Strategy 3: ProvidePlugin - Inject global polyfills
      config.plugins.push(
        new webpack.ProvidePlugin({
          Buffer: ['buffer', 'Buffer'],
          process: 'process/browser',
        })
      );

      // Strategy 4: IgnorePlugin - Suppress warnings for optional dependencies
      config.plugins.push(
        new webpack.IgnorePlugin({
          resourceRegExp: /^(bufferutil|utf-8-validate|encoding)$/,
        })
      );
    }

    // ==================================================
    // SERVER-SIDE: External optimization
    // ==================================================
    if (isServer) {
      // Mark heavy packages as external to reduce server bundle size
      config.externals = config.externals || [];
      config.externals.push({
        'puppeteer': 'commonjs puppeteer',
        'sharp': 'commonjs sharp',
        'canvas': 'commonjs canvas',
      });
    }

    // Production optimizations
    if (!dev && !isServer) {
      // Advanced code splitting
      config.optimization = {
        ...config.optimization,
        splitChunks: {
          chunks: 'all',
          cacheGroups: {
            // Framework chunk (React, Next.js)
            framework: {
              name: 'framework',
              test: /[\\/]node_modules[\\/](react|react-dom|next)[\\/]/,
              priority: 40,
              enforce: true,
            },
            // UI libraries chunk
            ui: {
              name: 'ui-libs',
              test: /[\\/]node_modules[\\/](framer-motion|@headlessui|@heroicons|lucide-react)[\\/]/,
              priority: 30,
              enforce: true,
            },
            // Charts chunk
            charts: {
              name: 'charts',
              test: /[\\/]node_modules[\\/](chart\.js|recharts|react-chartjs-2)[\\/]/,
              priority: 25,
              enforce: true,
            },
            // 3D libraries chunk (lazy load recommended)
            three: {
              name: 'three',
              test: /[\\/]node_modules[\\/](three|@react-three)[\\/]/,
              priority: 25,
              enforce: true,
            },
            // AI/ML chunk (lazy load recommended)
            ai: {
              name: 'ai-ml',
              test: /[\\/]node_modules[\\/](@tensorflow|groq-sdk)[\\/]/,
              priority: 25,
              enforce: true,
            },
            // Utilities chunk
            utils: {
              name: 'utils',
              test: /[\\/]node_modules[\\/](date-fns|lodash|axios)[\\/]/,
              priority: 20,
              minChunks: 1,
            },
            // Common vendor chunk
            vendor: {
              name: 'vendor',
              test: /[\\/]node_modules[\\/]/,
              priority: 10,
              minChunks: 2,
            },
            // Common app code
            common: {
              name: 'common',
              minChunks: 2,
              priority: 5,
              reuseExistingChunk: true,
            },
          },
        },
      };

      // Tree shaking optimization
      config.optimization.usedExports = true;
      config.optimization.sideEffects = true;
    }

    return config;
  },

  // Image optimization - Mobile-first, aggressive caching
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 60, // 60 days for better mobile caching
    // Quality settings for mobile
    quality: 80, // Balanced quality/size
    // Loader config for better performance
    loader: 'default',
    // Optimize for mobile networks
    disableStaticImages: false,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.pexels.com',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'source.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'api.dicebear.com',
      },
      {
        protocol: 'https',
        hostname: 'cdn.pixabay.com',
      },
      {
        protocol: 'https',
        hostname: '**.githubusercontent.com',
      },
      {
        protocol: 'https',
        hostname: 'res.cloudinary.com',
      },
      {
        protocol: 'https',
        hostname: 'cdn.ailydian.com',
      },
    ],
    unoptimized: false,
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },

  // Compression
  compress: true,

  // Headers for SEO and security
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          // Security headers
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
          {
            key: 'Referrer-Policy',
            value: 'origin-when-cross-origin',
          },
          // Content Security Policy
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://vercel.live https://va.vercel-scripts.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "img-src 'self' data: https: blob:",
              "font-src 'self' data: https://fonts.gstatic.com",
              "connect-src 'self' https://vercel.live https://*.vercel.app https://*.vercel-insights.com https://api.groq.com https://api.openai.com",
              "frame-src 'self' https://vercel.live",
              "media-src 'self' https:",
              "worker-src 'self' blob:",
            ].join('; '),
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self)',
          },
        ],
      },
      // Static assets - Aggressive caching
      {
        source: '/static/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
      // Next.js images - Aggressive caching
      {
        source: '/_next/image',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
      // API routes - Short cache
      {
        source: '/api/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-store, must-revalidate',
          },
        ],
      },
    ];
  },

  // Redirects for SEO
  async redirects() {
    return [
      // Add your redirects here
    ];
  },

  // Rewrites for clean URLs
  async rewrites() {
    return [
      // Add your rewrites here
    ];
  },
};

// Power user features
nextConfig.poweredByHeader = false;

// Environment variables exposed to client
nextConfig.env = {
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_SITE_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://travel.ailydian.com',
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'https://travel.ailydian.com/api',
};

// Production optimizations
if (process.env.NODE_ENV === 'production') {
  // Disable source maps in production for better performance
  nextConfig.productionBrowserSourceMaps = false;

  // Output standalone for better performance on Vercel
  nextConfig.output = 'standalone';
}

// Sentry configuration for error tracking and performance monitoring
const sentryConfig = {
  // Enable Sentry source maps upload during build
  org: 'ailydian',
  project: 'travel-lydian',

  // Only upload source maps if auth token is available (for CI/CD)
  authToken: process.env.SENTRY_AUTH_TOKEN,

  // Suppress telemetry during build
  telemetry: false,

  // Silent mode - suppress warnings during build
  silent: true,

  // Hide source maps from browser DevTools
  hideSourceMaps: true,

  // Suppress auth token warnings in development
  widenClientFileUpload: true,

  // Webpack configuration for Sentry
  webpack: {
    treeshake: {
      // Remove debug logging in production
      removeDebugLogging: true,
    },
  },
};

module.exports = withBundleAnalyzer(
  withSentryConfig(nextConfig, sentryConfig)
);
