import { PrismaClient, CarCategory, TransmissionType, FuelType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚗 Starting Car Rentals Seeding...\n');

  // Sample car rentals data - 15 diverse vehicles
  const cars = [
    // ECONOMY SEDANS (3)
    {
      name: 'Toyota Corolla 2023 - Ekonomik Sedan',
      slug: 'toyota-corolla-2023',
      description: 'Yakıt tasarruflu, güvenilir ve konforlu Toyota Corolla. Şehir içi ve şehirlerarası yolculuklar için ideal. Otomatik vites, klima ve modern güvenlik özellikleriyle donatılmış.',
      shortDescription: 'Ekonomik ve güvenilir sedan',
      brand: 'Toyota',
      model: 'Corolla',
      year: 2023,
      category: 'ECONOMY_SEDAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'GASOLINE' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 2,
      features: ['Bluetooth', 'USB Şarj', 'Çocuk Koltuğu Uyumlu', 'Cruise Control'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 450,
      pricePerWeek: 2800,
      pricePerMonth: 10000,
      currency: 'TRY',
      deposit: 1000,
      insuranceIncluded: true,
      insuranceType: 'Kask + Kasko',
      pickupLocations: ['İstanbul Havalimanı', 'Ankara', 'İzmir', 'Antalya'],
      allowDifferentDropoff: true,
      availableCount: 5,
      isAvailable: true,
      mainImage: '/images/cars/toyota-corolla.jpg',
      images: ['/images/cars/toyota-corolla.jpg', '/images/cars/toyota-corolla-2.jpg'],
      minimumAge: 21,
      drivingLicenseYears: 1,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      rating: 4.6,
      reviewCount: 124,
      metaTitle: 'Toyota Corolla 2023 Kiralama - Ekonomik Sedan',
      metaDescription: 'Toyota Corolla 2023 model kiralık araç. Ekonomik, güvenilir ve konforlu. Havalimanı teslimat mevcut.',
      keywords: ['toyota', 'corolla', 'ekonomik araç', 'sedan kiralama'],
    },
    {
      name: 'Honda Civic 2023 - Modern Sedan',
      slug: 'honda-civic-2023',
      description: 'Şık tasarımı ve ekonomik yakıt tüketimiyle Honda Civic. Geniş iç hacmi, konforlu koltukları ve gelişmiş teknolojileriyle uzun yolculuklar için mükemmel seçim.',
      shortDescription: 'Şık ve modern sedan',
      brand: 'Honda',
      model: 'Civic',
      year: 2023,
      category: 'ECONOMY_SEDAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'GASOLINE' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 2,
      features: ['Apple CarPlay', 'Android Auto', 'Geri Görüş Kamerası', 'Otopark Sensörü'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 480,
      pricePerWeek: 3000,
      pricePerMonth: 11000,
      currency: 'TRY',
      deposit: 1000,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir'],
      allowDifferentDropoff: true,
      availableCount: 4,
      isAvailable: true,
      mainImage: '/images/cars/honda-civic.jpg',
      images: ['/images/cars/honda-civic.jpg'],
      minimumAge: 22,
      drivingLicenseYears: 2,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      rating: 4.7,
      reviewCount: 98,
      metaTitle: 'Honda Civic 2023 Kiralama - Modern Sedan',
      metaDescription: 'Honda Civic 2023 araç kiralama. Şık tasarım, ekonomik yakıt tüketimi.',
      keywords: ['honda', 'civic', 'sedan', 'araç kiralama'],
    },
    {
      name: 'Hyundai Elantra 2024 - Yeni Nesil Sedan',
      slug: 'hyundai-elantra-2024',
      description: '2024 model Hyundai Elantra ile konfor ve teknoloji bir arada. Hybrid motor seçeneği ile düşük yakıt tüketimi, geniş iç mekan ve zengin donanım paketi.',
      shortDescription: 'Hybrid ekonomik sedan',
      brand: 'Hyundai',
      model: 'Elantra',
      year: 2024,
      category: 'ECONOMY_SEDAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'HYBRID' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 2,
      features: ['Hybrid Motor', 'Akıllı Sürüş Asistanı', 'Kablosuz Şarj', 'Panoramik Cam Tavan'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 550,
      pricePerWeek: 3500,
      pricePerMonth: 13000,
      currency: 'TRY',
      deposit: 1500,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir', 'Bodrum'],
      allowDifferentDropoff: true,
      availableCount: 3,
      isAvailable: true,
      mainImage: '/images/cars/hyundai-elantra.jpg',
      images: ['/images/cars/hyundai-elantra.jpg'],
      minimumAge: 23,
      drivingLicenseYears: 2,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      rating: 4.8,
      reviewCount: 56,
      metaTitle: 'Hyundai Elantra 2024 Hybrid Kiralama',
      metaDescription: '2024 Hyundai Elantra Hybrid kiralık araç. Düşük yakıt tüketimi, yeni teknolojiler.',
      keywords: ['hyundai', 'elantra', 'hybrid', '2024'],
    },

    // PREMIUM SEDANS (2)
    {
      name: 'BMW 3 Serisi 2024 - Premium Sedan',
      slug: 'bmw-3-series-2024',
      description: 'Prestijli BMW 3 Serisi ile lüks ve performans bir arada. Deri koltuklar, premium ses sistemi, gelişmiş sürüş dinamikleri ve üstün konfor.',
      shortDescription: 'Premium Alman sedanı',
      brand: 'BMW',
      model: '3 Series',
      year: 2024,
      category: 'PREMIUM_SEDAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 3,
      features: ['Deri Döşeme', 'Harman Kardon Ses', 'Adaptif Süspansiyon', 'Head-Up Display', '360 Derece Kamera'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 1200,
      pricePerWeek: 7500,
      pricePerMonth: 28000,
      currency: 'TRY',
      deposit: 3000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko + Ferdi Kaza',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir'],
      allowDifferentDropoff: true,
      availableCount: 2,
      isAvailable: true,
      mainImage: '/images/cars/bmw-3-series.jpg',
      images: ['/images/cars/bmw-3-series.jpg', '/images/cars/bmw-3-series-2.jpg'],
      minimumAge: 25,
      drivingLicenseYears: 3,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı', 'İkinci Kredi Kartı'],
      unlimitedMileage: false,
      mileageLimit: 3000,
      isActive: true,
      isFeatured: true,
      isPopular: true,
      rating: 4.9,
      reviewCount: 87,
      metaTitle: 'BMW 3 Serisi 2024 Kiralama - Premium Sedan',
      metaDescription: 'BMW 3 Serisi 2024 lüks araç kiralama. Prestijli, konforlu ve performans odaklı.',
      keywords: ['bmw', '3 series', 'premium', 'lüks araç'],
    },
    {
      name: 'Audi A4 2024 - İş ve Konfor',
      slug: 'audi-a4-2024',
      description: 'Audi A4 ile iş ve özel hayatınızda fark yaratın. Quattro 4x4 sistemi, Virtual Cockpit, premium iç tasarım ve güçlü motor seçenekleri.',
      shortDescription: 'Premium iş sedanı',
      brand: 'Audi',
      model: 'A4',
      year: 2024,
      category: 'PREMIUM_SEDAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 3,
      features: ['Quattro 4x4', 'Virtual Cockpit', 'Matrix LED', 'Masaj Koltuklar', 'Bang & Olufsen Ses'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 1300,
      pricePerWeek: 8000,
      pricePerMonth: 30000,
      currency: 'TRY',
      deposit: 3500,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko',
      pickupLocations: ['İstanbul', 'Ankara'],
      allowDifferentDropoff: false,
      availableCount: 2,
      isAvailable: true,
      mainImage: '/images/cars/audi-a4.jpg',
      images: ['/images/cars/audi-a4.jpg'],
      minimumAge: 26,
      drivingLicenseYears: 4,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı', 'İkinci Kredi Kartı'],
      unlimitedMileage: false,
      mileageLimit: 2500,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      rating: 4.9,
      reviewCount: 72,
      metaTitle: 'Audi A4 2024 Kiralama - Premium İş Sedanı',
      metaDescription: 'Audi A4 2024 kiralık araç. Quattro 4x4, lüks donanım, prestijli tasarım.',
      keywords: ['audi', 'a4', 'premium', 'quattro'],
    },

    // ECONOMY SUVs (2)
    {
      name: 'Dacia Duster 2023 - Uygun SUV',
      slug: 'dacia-duster-2023',
      description: 'Ekonomik ve spacious Dacia Duster. Aileler için ideal, geniş bagaj, yüksek sürüş pozisyonu ve uygun fiyat. Şehir içi ve doğa gezileri için mükemmel.',
      shortDescription: 'Ekonomik aile SUV',
      brand: 'Dacia',
      model: 'Duster',
      year: 2023,
      category: 'ECONOMY_SUV' as CarCategory,
      transmission: 'MANUAL' as TransmissionType,
      fuelType: 'GASOLINE' as FuelType,
      seats: 5,
      doors: 5,
      luggage: 3,
      features: ['Yüksek Sürüş Pozisyonu', 'Geniş Bagaj', 'Çocuk Koltuğu', '4x2'],
      airConditioning: true,
      gps: false,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 550,
      pricePerWeek: 3500,
      pricePerMonth: 12000,
      currency: 'TRY',
      deposit: 1500,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir', 'Antalya', 'Bodrum'],
      allowDifferentDropoff: true,
      availableCount: 6,
      isAvailable: true,
      mainImage: '/images/cars/dacia-duster.jpg',
      images: ['/images/cars/dacia-duster.jpg'],
      minimumAge: 22,
      drivingLicenseYears: 2,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      rating: 4.4,
      reviewCount: 156,
      metaTitle: 'Dacia Duster 2023 Kiralama - Ekonomik SUV',
      metaDescription: 'Dacia Duster SUV kiralama. Uygun fiyat, geniş iç hacim, aile dostu.',
      keywords: ['dacia', 'duster', 'suv', 'ekonomik'],
    },
    {
      name: 'Renault Captur 2024 - Kompakt SUV',
      slug: 'renault-captur-2024',
      description: 'Modern ve şık Renault Captur. Kompakt boyutları ile şehir içi kullanımda pratik, SUV konforu ve yüksek bagaj kapasitesi. Hybrid seçeneği mevcut.',
      shortDescription: 'Kompakt şehir SUV',
      brand: 'Renault',
      model: 'Captur',
      year: 2024,
      category: 'ECONOMY_SUV' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'HYBRID' as FuelType,
      seats: 5,
      doors: 5,
      luggage: 2,
      features: ['Hybrid Motor', 'Easy Park Assist', 'LED Farlar', 'Dijital Gösterge'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 600,
      pricePerWeek: 3800,
      pricePerMonth: 14000,
      currency: 'TRY',
      deposit: 1500,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir'],
      allowDifferentDropoff: true,
      availableCount: 4,
      isAvailable: true,
      mainImage: '/images/cars/renault-captur.jpg',
      images: ['/images/cars/renault-captur.jpg'],
      minimumAge: 23,
      drivingLicenseYears: 2,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: false,
      rating: 4.5,
      reviewCount: 89,
      metaTitle: 'Renault Captur 2024 Hybrid Kiralama - Kompakt SUV',
      metaDescription: 'Renault Captur 2024 SUV kiralama. Hybrid, ekonomik, şehir için ideal.',
      keywords: ['renault', 'captur', 'suv', 'hybrid'],
    },

    // PREMIUM SUVs (2)
    {
      name: 'BMW X5 2024 - Premium SUV',
      slug: 'bmw-x5-2024',
      description: 'Lüks ve performansın zirvesi BMW X5. 7 kişilik geniş iç mekan, xDrive 4x4 sistemi, premium deri döşeme ve son teknoloji güvenlik özellikleri.',
      shortDescription: '7 kişilik lüks SUV',
      brand: 'BMW',
      model: 'X5',
      year: 2024,
      category: 'PREMIUM_SUV' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 7,
      doors: 5,
      luggage: 4,
      features: ['xDrive 4x4', '7 Koltuk', 'Harman Kardon', 'Panoramik Tavan', 'Hava Süspansiyon', 'Masaj Koltuklar'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 1800,
      pricePerWeek: 11000,
      pricePerMonth: 40000,
      currency: 'TRY',
      deposit: 5000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko + Mini Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir'],
      allowDifferentDropoff: true,
      availableCount: 2,
      isAvailable: true,
      mainImage: '/images/cars/bmw-x5.jpg',
      images: ['/images/cars/bmw-x5.jpg', '/images/cars/bmw-x5-2.jpg'],
      minimumAge: 27,
      drivingLicenseYears: 5,
      requiredDocuments: ['Kimlik', 'Ehliyet', '2 Kredi Kartı', 'İkametgah'],
      unlimitedMileage: false,
      mileageLimit: 2000,
      isActive: true,
      isFeatured: true,
      isPopular: true,
      rating: 4.9,
      reviewCount: 67,
      metaTitle: 'BMW X5 2024 Kiralama - 7 Kişilik Lüks SUV',
      metaDescription: 'BMW X5 2024 premium SUV kiralama. 7 kişilik, 4x4, lüks donanım.',
      keywords: ['bmw', 'x5', 'suv', '7 kişilik', 'premium'],
    },
    {
      name: 'Range Rover Evoque 2024 - Lüks Kompakt SUV',
      slug: 'range-rover-evoque-2024',
      description: 'İngiliz lüksü Range Rover Evoque. Şık tasarım, üstün off-road kabiliyeti, premium iç mekan ve son teknoloji multimedya sistemi.',
      shortDescription: 'İngiliz lüks SUV',
      brand: 'Land Rover',
      model: 'Range Rover Evoque',
      year: 2024,
      category: 'PREMIUM_SUV' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'HYBRID' as FuelType,
      seats: 5,
      doors: 5,
      luggage: 3,
      features: ['Terrain Response', 'Meridian Ses', 'ClearSight Cam', 'Adaptif LED', 'Deri Döşeme'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 2000,
      pricePerWeek: 12500,
      pricePerMonth: 45000,
      currency: 'TRY',
      deposit: 6000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko',
      pickupLocations: ['İstanbul', 'Bodrum'],
      allowDifferentDropoff: false,
      availableCount: 1,
      isAvailable: true,
      mainImage: '/images/cars/range-rover-evoque.jpg',
      images: ['/images/cars/range-rover-evoque.jpg'],
      minimumAge: 28,
      drivingLicenseYears: 5,
      requiredDocuments: ['Kimlik', 'Ehliyet', '2 Kredi Kartı'],
      unlimitedMileage: false,
      mileageLimit: 1500,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      rating: 5.0,
      reviewCount: 34,
      metaTitle: 'Range Rover Evoque 2024 Kiralama - Lüks SUV',
      metaDescription: 'Range Rover Evoque 2024 lüks SUV kiralama. İngiliz prestiji, üstün konfor.',
      keywords: ['range rover', 'evoque', 'lüks', 'suv'],
    },

    // LUXURY (2)
    {
      name: 'Mercedes-Benz S-Class 2024 - Ultimate Luxury',
      slug: 'mercedes-s-class-2024',
      description: 'Otomobil lüksünün zirvesi Mercedes-Benz S-Class. Executive koltuklar, Burmester 3D ses sistemi, otonom sürüş özellikleri ve eşsiz konfor.',
      shortDescription: 'Lüksün zirvesi',
      brand: 'Mercedes-Benz',
      model: 'S-Class',
      year: 2024,
      category: 'LUXURY' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'HYBRID' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 3,
      features: ['Executive Koltuklar', 'Burmester 3D Ses', 'MBUX AR', 'E-Active Body', 'Ambient LED 64 Renk'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 3500,
      pricePerWeek: 22000,
      pricePerMonth: 80000,
      currency: 'TRY',
      deposit: 10000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko + Ferdi Kaza + Mini Kasko',
      pickupLocations: ['İstanbul'],
      allowDifferentDropoff: false,
      availableCount: 1,
      isAvailable: true,
      mainImage: '/images/cars/mercedes-s-class.jpg',
      images: ['/images/cars/mercedes-s-class.jpg', '/images/cars/mercedes-s-class-2.jpg'],
      minimumAge: 30,
      drivingLicenseYears: 7,
      requiredDocuments: ['Kimlik', 'Ehliyet', '2 Kredi Kartı', 'Gelir Belgesi'],
      unlimitedMileage: false,
      mileageLimit: 1000,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      rating: 5.0,
      reviewCount: 45,
      metaTitle: 'Mercedes-Benz S-Class 2024 Kiralama - Ultimate Luxury',
      metaDescription: 'Mercedes S-Class 2024 lüks araç kiralama. Lüksün zirvesi, eşsiz konfor.',
      keywords: ['mercedes', 's-class', 'lüks', 'executive'],
    },
    {
      name: 'Audi A8 2024 - Business Luxury',
      slug: 'audi-a8-2024',
      description: 'İş dünyasının tercihi Audi A8. Quattro 4x4, uzun dingil mesafesi, relax koltuklar ve Audi AI teknolojileriyle mükemmel sürüş deneyimi.',
      shortDescription: 'İş dünyası lüksü',
      brand: 'Audi',
      model: 'A8',
      year: 2024,
      category: 'LUXURY' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 3,
      features: ['Quattro 4x4', 'Relax Koltuklar', 'Matrix LED', 'Bang & Olufsen 3D', 'AI Sürüş Asistanı'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 3200,
      pricePerWeek: 20000,
      pricePerMonth: 75000,
      currency: 'TRY',
      deposit: 8000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko',
      pickupLocations: ['İstanbul', 'Ankara'],
      allowDifferentDropoff: false,
      availableCount: 1,
      isAvailable: true,
      mainImage: '/images/cars/audi-a8.jpg',
      images: ['/images/cars/audi-a8.jpg'],
      minimumAge: 30,
      drivingLicenseYears: 7,
      requiredDocuments: ['Kimlik', 'Ehliyet', '2 Kredi Kartı'],
      unlimitedMileage: false,
      mileageLimit: 1200,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      rating: 4.9,
      reviewCount: 38,
      metaTitle: 'Audi A8 2024 Kiralama - Business Luxury Sedan',
      metaDescription: 'Audi A8 2024 lüks sedan kiralama. İş dünyası için ideal, üstün konfor.',
      keywords: ['audi', 'a8', 'lüks', 'business'],
    },

    // SPORTS (1)
    {
      name: 'Porsche 911 Carrera 2024 - Sports Icon',
      slug: 'porsche-911-carrera-2024',
      description: 'Efsanevi Porsche 911 Carrera. 450 HP güç, 0-100 km/s 3.8 saniye, spor egzoz sistemi ve adrenalin dolu sürüş deneyimi.',
      shortDescription: 'Efsanevi spor otomobil',
      brand: 'Porsche',
      model: '911 Carrera',
      year: 2024,
      category: 'SPORTS' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'GASOLINE' as FuelType,
      seats: 4,
      doors: 2,
      luggage: 1,
      features: ['450 HP', 'Sport Chrono', 'PASM Süspansiyon', 'Bose Ses', 'Sport Egzoz'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 5000,
      pricePerWeek: 32000,
      pricePerMonth: 120000,
      currency: 'TRY',
      deposit: 15000,
      insuranceIncluded: true,
      insuranceType: 'Tam Kasko + Özel Sigorta',
      pickupLocations: ['İstanbul'],
      allowDifferentDropoff: false,
      availableCount: 1,
      isAvailable: true,
      mainImage: '/images/cars/porsche-911.jpg',
      images: ['/images/cars/porsche-911.jpg', '/images/cars/porsche-911-2.jpg'],
      minimumAge: 30,
      drivingLicenseYears: 8,
      requiredDocuments: ['Kimlik', 'Ehliyet', '2 Kredi Kartı', 'Track Day Deneyim Belgesi (Opsiyonel)'],
      unlimitedMileage: false,
      mileageLimit: 500,
      isActive: true,
      isFeatured: true,
      isPopular: true,
      rating: 5.0,
      reviewCount: 29,
      metaTitle: 'Porsche 911 Carrera 2024 Kiralama - Sports Car',
      metaDescription: 'Porsche 911 Carrera 2024 spor araç kiralama. 450 HP, efsanevi performans.',
      keywords: ['porsche', '911', 'sports car', 'carrera'],
    },

    // VAN / MINIVAN (2)
    {
      name: 'Mercedes-Benz Vito 2023 - 9 Kişilik Van',
      slug: 'mercedes-vito-2023',
      description: 'Geniş aileler ve grup seyahatleri için Mercedes Vito. 9 kişilik konforlu koltuklar, geniş bagaj, klima ve multimedya sistemi.',
      shortDescription: '9 kişilik konforlu van',
      brand: 'Mercedes-Benz',
      model: 'Vito',
      year: 2023,
      category: 'VAN' as CarCategory,
      transmission: 'AUTOMATIC' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 9,
      doors: 5,
      luggage: 5,
      features: ['9 Kişilik', 'Klima', 'Multimedya', 'Geniş Bagaj', 'Cruise Control'],
      airConditioning: true,
      gps: true,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 900,
      pricePerWeek: 5500,
      pricePerMonth: 20000,
      currency: 'TRY',
      deposit: 2500,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir', 'Antalya'],
      allowDifferentDropoff: true,
      availableCount: 3,
      isAvailable: true,
      mainImage: '/images/cars/mercedes-vito.jpg',
      images: ['/images/cars/mercedes-vito.jpg'],
      minimumAge: 25,
      drivingLicenseYears: 3,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      rating: 4.7,
      reviewCount: 112,
      metaTitle: 'Mercedes Vito 2023 Kiralama - 9 Kişilik Van',
      metaDescription: 'Mercedes Vito 9 kişilik van kiralama. Grup seyahatleri için ideal, konforlu.',
      keywords: ['mercedes', 'vito', 'van', '9 kişilik'],
    },
    {
      name: 'Volkswagen Transporter 2023 - Çok Amaçlı Van',
      slug: 'volkswagen-transporter-2023',
      description: 'Güvenilir VW Transporter. 8+1 koltuk, geniş iç hacim, yük ve yolcu taşıma esnekliği. Uzun yolculuklar için konforlu.',
      shortDescription: '8+1 çok amaçlı van',
      brand: 'Volkswagen',
      model: 'Transporter',
      year: 2023,
      category: 'MINIVAN' as CarCategory,
      transmission: 'MANUAL' as TransmissionType,
      fuelType: 'DIESEL' as FuelType,
      seats: 9,
      doors: 5,
      luggage: 6,
      features: ['8+1 Koltuk', 'Yük Alanı', 'Klima', 'Radio/CD', 'ESP'],
      airConditioning: true,
      gps: false,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 750,
      pricePerWeek: 4800,
      pricePerMonth: 18000,
      currency: 'TRY',
      deposit: 2000,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir'],
      allowDifferentDropoff: true,
      availableCount: 4,
      isAvailable: true,
      mainImage: '/images/cars/vw-transporter.jpg',
      images: ['/images/cars/vw-transporter.jpg'],
      minimumAge: 24,
      drivingLicenseYears: 3,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: false,
      rating: 4.5,
      reviewCount: 94,
      metaTitle: 'VW Transporter 2023 Kiralama - 8+1 Van',
      metaDescription: 'Volkswagen Transporter van kiralama. Çok amaçlı, güvenilir, geniş hacim.',
      keywords: ['volkswagen', 'transporter', 'van', 'minivan'],
    },

    // COMPACT (1)
    {
      name: 'Fiat Egea 2023 - Kompakt Sedan',
      slug: 'fiat-egea-2023',
      description: 'Ekonomik ve pratik Fiat Egea. Şehir içi kullanım için ideal, kolay park, düşük yakıt tüketimi ve geniş iç hacim.',
      shortDescription: 'Ekonomik şehir arabası',
      brand: 'Fiat',
      model: 'Egea',
      year: 2023,
      category: 'COMPACT' as CarCategory,
      transmission: 'MANUAL' as TransmissionType,
      fuelType: 'GASOLINE' as FuelType,
      seats: 5,
      doors: 4,
      luggage: 2,
      features: ['Yakıt Tasarruflu', 'Bluetooth', 'Elektrikli Camlar', 'ABS'],
      airConditioning: true,
      gps: false,
      bluetooth: true,
      usbCharger: true,
      pricePerDay: 380,
      pricePerWeek: 2400,
      pricePerMonth: 8500,
      currency: 'TRY',
      deposit: 800,
      insuranceIncluded: true,
      insuranceType: 'Kasko',
      pickupLocations: ['İstanbul', 'Ankara', 'İzmir', 'Antalya', 'Bodrum', 'Muğla'],
      allowDifferentDropoff: true,
      availableCount: 8,
      isAvailable: true,
      mainImage: '/images/cars/fiat-egea.jpg',
      images: ['/images/cars/fiat-egea.jpg'],
      minimumAge: 21,
      drivingLicenseYears: 1,
      requiredDocuments: ['Kimlik', 'Ehliyet', 'Kredi Kartı'],
      unlimitedMileage: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      rating: 4.3,
      reviewCount: 187,
      metaTitle: 'Fiat Egea 2023 Kiralama - Ekonomik Kompakt',
      metaDescription: 'Fiat Egea 2023 ekonomik araç kiralama. Şehir için ideal, uygun fiyat.',
      keywords: ['fiat', 'egea', 'compact', 'ekonomik'],
    },
  ];

  // Create cars
  for (const carData of cars) {
    try {
      const car = await prisma.carRental.create({
        data: carData,
      });
      console.log(`✅ Created car: ${car.name}`);
    } catch (error: any) {
      console.error(`❌ Error creating car: ${carData.name}`, error.message);
    }
  }

  console.log(`\n✅ Car Rentals Seeding Completed! ${cars.length} cars added.`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
