// Mock implementation for Node.js 'os' module in browser
module.exports = {
  platform: () => 'browser',
  type: () => 'Browser',
  release: () => '',
  arch: () => 'x64',
  tmpdir: () => '/tmp',
  homedir: () => '/home',
  hostname: () => 'localhost',
  endianness: () => 'LE',
  cpus: () => [],
  networkInterfaces: () => ({}),
  EOL: '\n',
  constants: {},
  totalmem: () => 0,
  freemem: () => 0,
  loadavg: () => [0, 0, 0],
  uptime: () => 0,
  userInfo: () => ({ username: 'user', homedir: '/home', shell: null, uid: -1, gid: -1 }),
};
